# Dependency Warning: Running this script requires the 'transitions' library.
# Install it using: pip install transitions

import os
import json
from transitions import Machine, MachineError

class CSALegalContract:
    def __init__(self, config: dict):
        self.config = config
        
        # Instantiate the state machine dynamically from the dict configuration
        self.machine = Machine(
            model=self,
            states=self.config["states"],
            initial=self.config["initial_state"],
            send_event=True  # Allows passing event data if needed later
        )
        
        # Programmatically populate transitions from the dict loop
        for trans in self.config["transitions"]:
            self.machine.add_transition(
                trigger=trans["trigger"],
                source=trans["source"],
                dest=trans["dest"]
            )

    def safe_trigger(self, trigger_name: str) -> bool:
        """
        Executes a state transition trigger. Catch MachineError 
        to ensure the downstream RL loop never abruptly crashes.
        """
        try:
            # Dynamically call the trigger method generated by the transitions library
            trigger_method = getattr(self, trigger_name)
            trigger_method()
            return True
        except (MachineError, AttributeError):
            # Return False indicating an illegal/invalid action was attempted
            return False

if __name__ == "__main__":
    # Load configuration from simple_automaton.json
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(script_dir, "simple_automaton.json")
    
    with open(config_path, "r") as f:
        config = json.load(f)

    # ----------------------------------------------------
    # Test Path 1 (Resolution):
    # normal -> observe_breach -> margin_call_issued -> receive_full_margin -> normal
    # ----------------------------------------------------
    contract1 = CSALegalContract(config)
    assert contract1.state == "normal"
    
    assert contract1.safe_trigger("observe_breach") is True
    assert contract1.state == "margin_call_issued"
    
    assert contract1.safe_trigger("receive_full_margin") is True
    assert contract1.state == "normal"
    print("Test Path 1 (Resolution) passed.")

    # ----------------------------------------------------
    # Test Path 2 (Default):
    # normal -> observe_breach -> margin_call_issued -> elapse_one_day -> grace_period -> miss_deadline -> default
    # ----------------------------------------------------
    contract2 = CSALegalContract(config)
    assert contract2.state == "normal"
    
    assert contract2.safe_trigger("observe_breach") is True
    assert contract2.state == "margin_call_issued"
    
    assert contract2.safe_trigger("elapse_one_day") is True
    assert contract2.state == "grace_period"
    
    assert contract2.safe_trigger("miss_deadline") is True
    assert contract2.state == "default"
    print("Test Path 2 (Default) passed.")

    # ----------------------------------------------------
    # Test Path 3 (Illegal Action Guard):
    # normal -> miss_deadline (illegal) -> returns False, state remains normal
    # ----------------------------------------------------
    contract3 = CSALegalContract(config)
    assert contract3.state == "normal"
    
    # Try calling a trigger that is invalid for the "normal" state
    assert contract3.safe_trigger("miss_deadline") is False
    assert contract3.state == "normal"
    
    # Try calling a completely non-existent trigger
    assert contract3.safe_trigger("non_existent_trigger") is False
    assert contract3.state == "normal"
    print("Test Path 3 (Illegal Action Guard) passed.")

    print("\nAll state machine path verification checks completed successfully!")
